@startuml
'https://plantuml.com/class-diagram

interface Displayer{
}

class Display{
}

class Bouncers{
}

interface Bouncable{
}

class BouncableShape{
}

class Square{
}

class Circle{
}

class CircleFilled{
}

class FactoryShape

interface Factory {
}

Bouncers --> Factory

Factory <- FactoryShape

FactoryShape <|-down- FactoryFilled
FactoryShape <|-down- FactoryStroke
FactoryFilled -> CircleFilled
FactoryFilled -> SquareFilled


FactoryStroke -> CircleStroke
FactoryStroke -> SquareStroke

class FactoryFilled {
}

class FactoryStroke {
}

class CircleStroke{
}

class SquareFilled{
}

class SquareStroke{
}

Displayer --> Display
Bouncers --> Display

Bouncable --> BouncableShape
BouncableShape <|-down- Square
BouncableShape <|-down- Circle
Circle <|-down- CircleFilled
Square <|-down- SquareFilled
Circle <|-down- CircleStroke
Square <|-down- SquareStroke

@enduml